steps:
  - label: "Format Python"
    command: ".buildkite/scripts/format-python.sh"
    plugins:
      - docker-compose#v4.14.0:
          run: tooling
          mount-ssh-agent: true
          mount-buildkite-agent: true
          propagate-environment: true
    agents:
      queue: "nano"

  - label: "Generate CLI docs"
    branches: "main"
    command: ".buildkite/scripts/generate-cli-docs.sh"
    plugins:
      - docker-compose#v4.14.0:
          run: tooling
          mount-ssh-agent: true
          mount-buildkite-agent: true
          propagate-environment: true
    agents:
      queue: "nano"

  - label: "Publish docker image"
#    branches: "main"
    branches: "publish-docker"
    plugins:
      - docker-compose#v4.14.0:
          push:
            - rank:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/rank:ref.${BUILDKITE_COMMIT}
            - rank:756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/rank:latest
    agents:
      queue: "nano"
