steps:
  - label: "format-python"
    command: ".buildkite/scripts/format-python.sh"
    plugins:
      - docker-compose#v4.11.0:
          run: tooling
          mount-ssh-agent: true
          mount-buildkite-agent: true
          propagate-environment: true
    agents:
      queue: "nano"
  - label: "generate-cli-docs"
    command: ".buildkite/scripts/generate-cli-docs.sh"
    plugins:
      - docker-compose#v4.11.0:
          run: tooling
          mount-ssh-agent: true
          mount-buildkite-agent: true
          propagate-environment: true
    agents:
      queue: "nano"
